_commit: 051ee00
_src_path: https://github.com/slaclab/lume-model-deployment-template.git
deployment_name: lcls-fel-surrogate-deployment
device: cpu
interface: epics
mlflow_tracking_uri: https://ard-mlflow.slac.stanford.edu/
model_version: 1
rate: 1.0
registered_model_name: lcls-fel-surrogate
